name:                bingo-sim
version:             0.0.5.0
homepage:            https://github.com/jez/bingo-sim
author:              Jake Zimmerman
maintainer:          zimmerman.jake@gmail.com
copyright:           2019 Jake Zimmerman
license:             MIT

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis: >
  A small playground to learn about profiling Haskell.
description: >
  This package simulates the probability of scoring a bingo at a particular
  children's carnival game. I've been using it to learn how profiling in
  Haskell works.
category: Simple

ghc-options:
- -Wall
- -Wcompat
- -Wmissing-signatures
- -Werror
- -funbox-strict-fields
- -O2

dependencies:
- base >=4.7 && <5
- random

library:
  source-dirs: src

executables:
  bingo-sim:
    main: Main.hs
    source-dirs: app
    dependencies:
    - bingo-sim
